# python run.py /mnt/sda/coex_data/track_fail/columbia/columbia_1
# python run.py /mnt/sda/coex_data/track_fail/columbia/columbia_2
# python run.py /mnt/sda/coex_data/track_fail/columbia/columbia_3
# python run.py /mnt/sda/coex_data/track_fail/columbia/columbia_r
# python run.py /mnt/sda/coex_data/track_fail/converse/converse_1
# python run.py /mnt/sda/coex_data/track_fail/converse/converse_2
# python run.py /mnt/sda/coex_data/track_fail/converse/converse_3
# python run.py /mnt/sda/coex_data/track_fail/converse/converse_r
# python run.py /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_1
# python run.py /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_2
# python run.py /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_3
# python run.py /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_r
# python run.py /mnt/sda/coex_data/track_fail/plantude/plantude_1
# python run.py /mnt/sda/coex_data/track_fail/plantude/plantude_2
# python run.py /mnt/sda/coex_data/track_fail/plantude/plantude_3
# python run.py /mnt/sda/coex_data/track_fail/plantude/plantude_r
# python run.py /mnt/sda/coex_data/track_fail/shake/shake_1
# python run.py /mnt/sda/coex_data/track_fail/shake/shake_2
# python run.py /mnt/sda/coex_data/track_fail/shake/shake_3
python run.py /mnt/sda/coex_data/track_fail/result_2025_02_07_103921

# rm -r /mnt/sda/coex_data/track_fail/columbia/columbia_2/compare_results
# rm -r /mnt/sda/coex_data/track_fail/columbia/columbia_2/ocr
# rm -r /mnt/sda/coex_data/track_fail/columbia/columbia_2/text
# rm -f /mnt/sda/coex_data/track_fail/columbia/columbia_2/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/columbia/columbia_3/compare_results
# rm -r /mnt/sda/coex_data/track_fail/columbia/columbia_3/ocr
# rm -r /mnt/sda/coex_data/track_fail/columbia/columbia_3/text
# rm -f /mnt/sda/coex_data/track_fail/columbia/columbia_3/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/columbia/columbia_r/compare_results
# rm -r /mnt/sda/coex_data/track_fail/columbia/columbia_r/ocr
# rm -r /mnt/sda/coex_data/track_fail/columbia/columbia_r/text
# rm -f /mnt/sda/coex_data/track_fail/columbia/columbia_r/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/converse/converse_1/compare_results
# rm -r /mnt/sda/coex_data/track_fail/converse/converse_1/ocr
# rm -r /mnt/sda/coex_data/track_fail/converse/converse_1/text
# rm -f /mnt/sda/coex_data/track_fail/converse/converse_1/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/converse/converse_2/compare_results
# rm -r /mnt/sda/coex_data/track_fail/converse/converse_2/ocr
# rm -r /mnt/sda/coex_data/track_fail/converse/converse_2/text
# rm -f /mnt/sda/coex_data/track_fail/converse/converse_2/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/converse/converse_3/compare_results
# rm -r /mnt/sda/coex_data/track_fail/converse/converse_3/ocr
# rm -r /mnt/sda/coex_data/track_fail/converse/converse_3/text
# rm -f /mnt/sda/coex_data/track_fail/converse/converse_3/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/converse/converse_r/compare_results
# rm -r /mnt/sda/coex_data/track_fail/converse/converse_r/ocr
# rm -r /mnt/sda/coex_data/track_fail/converse/converse_r/text
# rm -f /mnt/sda/coex_data/track_fail/converse/converse_r/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_1/compare_results
# rm -r /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_1/ocr
# rm -r /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_1/text
# rm -f /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_1/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_2/compare_results
# rm -r /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_2/ocr
# rm -r /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_2/text
# rm -f /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_2/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_3/compare_results
# rm -r /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_3/ocr
# rm -r /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_3/text
# rm -f /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_3/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_r/compare_results
# rm -r /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_r/ocr
# rm -r /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_r/text
# rm -f /mnt/sda/coex_data/track_fail/lifefourcut/lifefourcut_r/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/plantude/plantude_1/compare_results
# rm -r /mnt/sda/coex_data/track_fail/plantude/plantude_1/ocr
# rm -r /mnt/sda/coex_data/track_fail/plantude/plantude_1/text
# rm -f /mnt/sda/coex_data/track_fail/plantude/plantude_1/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/plantude/plantude_2/compare_results
# rm -r /mnt/sda/coex_data/track_fail/plantude/plantude_2/ocr
# rm -r /mnt/sda/coex_data/track_fail/plantude/plantude_2/text
# rm -f /mnt/sda/coex_data/track_fail/plantude/plantude_2/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/plantude/plantude_3/compare_results
# rm -r /mnt/sda/coex_data/track_fail/plantude/plantude_3/ocr
# rm -r /mnt/sda/coex_data/track_fail/plantude/plantude_3/text
# rm -f /mnt/sda/coex_data/track_fail/plantude/plantude_3/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/plantude/plantude_r/compare_results
# rm -r /mnt/sda/coex_data/track_fail/plantude/plantude_r/ocr
# rm -r /mnt/sda/coex_data/track_fail/plantude/plantude_r/text
# rm -f /mnt/sda/coex_data/track_fail/plantude/plantude_r/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/shake/shake_1/compare_results
# rm -r /mnt/sda/coex_data/track_fail/shake/shake_1/ocr
# rm -r /mnt/sda/coex_data/track_fail/shake/shake_1/text
# rm -f /mnt/sda/coex_data/track_fail/shake/shake_1/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/shake/shake_2/compare_results
# rm -r /mnt/sda/coex_data/track_fail/shake/shake_2/ocr
# rm -r /mnt/sda/coex_data/track_fail/shake/shake_2/text
# rm -f /mnt/sda/coex_data/track_fail/shake/shake_2/ocr_info.csv
# rm -r /mnt/sda/coex_data/track_fail/shake/shake_3/compare_results
# rm -r /mnt/sda/coex_data/track_fail/shake/shake_3/ocr
# rm -r /mnt/sda/coex_data/track_fail/shake/shake_3/text
# rm -f /mnt/sda/coex_data/track_fail/shake/shake_3/ocr_info.csv
